---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
"SISTER, sister, go to bed!   
Go and rest your weary head."   
Thus the prudent brother said.   
  
"Do you want a battered hide,   
Or scratches to your face applied?"


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Our teacher gave detention  
to the fountains in the hall.  
She handed extra homework  
to the artwork on the wall.  
 
We saw her point a finger  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
The room was suddenly rich and the great bay-window was  
Spawning snow and pink roses against it  
Soundlessly collateral and incompatible:  
World is suddener than we fancy it.  

World is crazier and more of it than we think,  
Incorrigibly plural. I peel and portion  
A tangerine and spit the pips and feel  
The drunkenness of things being various.  

And the fire flames with a bubbling sound for world  
Is more spiteful and gay than one supposes—   
On the tongue on the eyes on the ears in the palms of   one's hands—  
There is more than glass between the snow and the huge   roses.  